### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by martinx** [sjtu-cs/service-scraper#1]
选择你打算开发的语言，并配置好环境。成功后，请在下面留言，并注明选择的语言，目前考虑

* Python
* Ruby
* Java
* Node JS

**Comment by BlueSoraSky** [comment]
打算使用Python，请问哪个版本比较推荐

**Comment by martinx** [comment]
都可以的，对我们这个项目来说 Python 2.7, 3.x 都是可以的，如果不建议的话，就直接使用3.x版本吧。 @BlueSoraSky

**Comment by ppjerry** [comment]
老徐，你指的配置好环境是装好Python 2.7 或者3.x？还有指什么其他的环境配置吗？

**Comment by ppjerry** [comment]
我也用python

**Comment by martinx** [comment]
@ppjerry 没有其他配置了，只要能执行 Python 就可以了。
